# Generated by Django 3.2.22 on 2023-12-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('coverage', models.CharField(max_length=250)),
                ('suscriber', models.IntegerField()),
            ],
        ),
    ]
