# Generated by Django 4.2.5 on 2023-09-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudad',
            new_name='City',
        ),
    ]
