# Generated by Django 4.2.5 on 2023-09-25 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_rename_ciudad_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitacora.city')),
            ],
        ),
        migrations.CreateModel(
            name='Electric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('service_code', models.BigIntegerField()),
                ('telephone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, help_text='Formato: AAAA-BBBB-CCCC', max_length=14, null=True)),
                ('upstream', models.CharField(blank=True, max_length=8, null=True)),
                ('downstream', models.CharField(blank=True, max_length=8, null=True)),
                ('graph', models.URLField(blank=True, null=True)),
                ('cmts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitacora.cmts')),
                ('electric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitacora.electric')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, help_text='Formato: AAAA-BBBB-CCCC', max_length=14, null=True)),
                ('upstream', models.CharField(blank=True, max_length=8, null=True)),
                ('downstream', models.CharField(blank=True, max_length=8, null=True)),
                ('graph', models.URLField(blank=True, null=True)),
                ('cmts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitacora.cmts')),
            ],
        ),
    ]
