# Generated by Django 4.2.5 on 2023-09-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_cmts_electric_source_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electric',
            name='service_code',
        ),
        migrations.AddField(
            model_name='source',
            name='service_code',
            field=models.IntegerField(default=111111),
        ),
    ]
